name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: install dependencies
        run: pnpm install --force

      - name: build app
        run: pnpm run build

      - name: Deploy with PM2
        run: | 
          pm2 stop all || true
          pm2 start .output/server/index.mjs --name "nuxt-app"
          pm2 save
